### ISSUE TITLE
run deposit-bag-validator on more root 1  objects

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/moab-versioning#125]
It seems we should get more data about state of objects on storage root 1 before sizing up the work to migrate storage root 1 objects into actual Moabs.

@LynnMcRae @julianmorley might you be able to come up with a short list of druids that might exemplify different types of objects and/or different eras of objects on storage root 1?     All I have is blind "let's pick a druid starting ch" -- have you got any other tricks up your sleeve to select druids to run against the newly minted deposit-bag-validator?

(See also https://docs.google.com/document/d/1etLnmFK07u2RfPcQcDVBNnOkq53bsdTSbbHTY2gPB38 and sul-dlss/preservation_catalog/issues/70)

**Comment by ndushay** [comment]
Note that in the handlful of fixture objects from Lynn, there *may* be some old enough to be from the initial `/services-disk` ... but I don't think so

```
    druid:bj102hs9687 - ETD - 3 versions (2012-12-17, 2013-06-18, 2016-06-14) - 1.82 MB
    druid:dc048cw1328 - ETD - 3 versions (2012-12-17, 2013-06-18) - 4.88 MB
    druid:bp628nk4868 - EEMS - 1 version (2016-08-25) - 390 KB
    druid:bz514sm9647 - Image - 3 versions (2017-05-30, 2017-05-31, 2017-06-25) - 164 KB
```

**Comment by julianmorley** [comment]
I don't have any particular hints for target selection, I'm afraid.

**Comment by LynnMcRae** [comment]
Here's a few to start with. Is it the sort of this you are looking for? Volume 1 has a object date range of about 2 years.

Store01

—> Early

druid:tp344fm4182 — ETD
     registered 2010.01.26
     accessioned 2010.02
     ingested 2011-12-05
druid:rh637qq0237 — Google scanned book
     accessioned 2011.02.15
     ingested 2011.02.21

Has second version 

druid:xr653yx5197 - ETD
     registered 2011-05-16
     accessioned 2012-12-17
     accessioned 2017-03-02

—> Late

druid:qk015wc3060 — Google scanned book
     registered 2012-04-17
     ingested 2012-04-19

**Comment by ndushay** [comment]
I ran them through.  All were consistent; all are missing exactly the same files as the first example in the google doc.  From the google doc:

* manifest-sha256.txt
* tagmanifest-sha256.txt
* versionAdditions.xml
* versionInventory.xml
* data/metadata/versionMetadata.xml  ← which also requires an entry added to signatureCatalog.xml
