### ISSUE TITLE
(CV) Make FileSignature.from_file default algos configurable

### ISSUE THREAD

**Issue by atz** [sul-dlss/moab-versioning#142]
Properly configured, no second argument would be required to use a subset of known algos.  This prevents having to pass that list down through the overly nested stack described [here](https://github.com/sul-dlss/preservation_catalog/issues/39#issuecomment-363973215).  The default should change from `KNOWN_ALGOS.keys` to a method call like `default_algos` that respects configs.

It may be desirable to move the `KNOWN_ALGOS` constant out of `FileSignature` into a higher level of the gem, as mentioned here: https://github.com/sul-dlss/moab-versioning/pull/140/files#r180177533

Wherever it lives, the configurability definitely *should* be encapsulated with a method such that is NOT fiddling with the constant.  It is unclear (to me) how many other parts of code might usefully rely on the same or similar configurability.

**Comment by ndushay** [comment]
See also #143
