### ISSUE TITLE
'Identifier has invalid suri syntax' error should have its own class

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/moab-versioning#159]
if it were a subclass of `StandardError`, it'd be easier to trap.  see:
https://github.com/sul-dlss/moab-versioning/blob/6f0759e382647399db5eddc4d94dad5bfeeef400/lib/stanford/storage_repository.rb#L29-L39

for expediency, we've trapped and re-cast this as a more specific error in some pres cat work (see https://github.com/sul-dlss/preservation_catalog/pull/1207).  because it makes the error handling in that controller easier.  but really, that should be happening in this code base.

i don't _think_ this requires a major version bump, because anything that was previously trapping `StandardError` (which is what is raised now) would also be able to trap a subclass of `StandardError` without changing the code.  and if the error message is retained, then any examination of said message would still work.

**Comment by ndushay** [comment]
Actually, it raises RuntimeError (a subclass of StandardError)
