### ISSUE TITLE
Moab::StorageRepository#search_storage_objects returns duplicate results if object is mid-deposit

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/moab-versioning#167]
`Moab::StorageRepository#search_storage_objects` will return what is essentially the same storage object result twice if the object is in the storage trunk for a storage root, but also in the deposit folder for the storage root, which will be the case when the object has been copied to the storage root but not yet cleaned up from the deposit folder (which, afaict, doesn't happen till after pres robots makes a REST call to pres cat to inform it of the versioned moab).

for a given storage root `Moab::StorageRepository#search_storage_objects` should return at most one result for a druid.  even in the situation where the calling code wants to get the deposit folder, it can get that using the `Moab::StorageObject#.deposit_bag_pathname` method, as pres robots does).

i can think of a couple possible ways to fix this:
1. consolidate the two loops in the `#search_storage_objects` method:  search the `storage_trunk` as the first loop does, and if the object is found, do the `storage_objects << create_storage_object(object_id, root)`, and move to the next iteration of the loop (the next storage root); if the moab isn't in that root's storage trunk and `include_deposit` is `true`, search the `deposit` dir, and do the `storage_objects << create_storage_object(object_id, root)`, and fall through to the next loop iteration.
1. add a `Moab::StorageObject#eql?` method (comparing `StorageObject#digital_object_id`, `#object_pathname`, and `#storage_root`).
  1. and return `storage_objects#uniq` from `Moab::StorageRepository#search_storage_objects`

i think i'd lean towards number 1, since i think it would make Moab::StorageRepository#search_storage_objects both more efficient and more readable, but i'd be fine with either.

**Comment by ndushay** [comment]
closing this as #198 is about removing this very code.
