### ISSUE TITLE
Consolidate develop branch against master

### ISSUE THREAD

**Issue by darrenleeweber** [sul-dlss/moab-versioning#17]
The `develop` branch can be removed, so long as the commits are consolidated in master (if not already).  At the time of writing, it looks like it was only 1 commit ahead of master.

**Comment by jmartin-sul** [comment]
at present, develop does indeed appear to be one commit ahead of master, but it's just a merge commit, and git detects no actual difference between the two branches:
https://github.com/sul-dlss/moab-versioning/compare/master...develop
![screen shot 2017-08-23 at 11 54 05 am](https://user-images.githubusercontent.com/7741604/29633093-fcc1843e-87f9-11e7-9d61-2520add5d2c3.png)

as such, i'm inclined to just delete the develop branch.

**Comment by jmartin-sul** [comment]
and indeed, pulling develop onto master would just add the merge commit, with no code changes:  https://github.com/sul-dlss/moab-versioning/pull/18

**Comment by ndushay** [comment]
I'm closing this ticket and removing the branch.
