### ISSUE TITLE
deprecate and remove find_storage_object

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/moab-versioning#190]
Now that we have `search_storage_objects` (for "multi-moab" objects), we should use it consistently.  A multi-moab object could return an incorrect primary item if you call find_storage_object on it.

Some places that need to be updated:
* https://github.com/sul-dlss/moab-versioning/blob/1cfe59cfb4f9fea7a1cc35b936a8f5a7ddd94029/lib/moab/storage_repository.rb#L138
* https://github.com/sul-dlss/preservation_catalog/blob/f80babe531fd61f80985e797bfc08237b2449b15/app/jobs/validate_moab_job.rb#L81
* https://github.com/sul-dlss/technical-metadata-service/blob/f28bb14418ca9095e991e3affa2202298694673f/app/services/moab_processing_service.rb#L25
* https://github.com/sul-dlss/preservation_robots/blob/32513e9a0a465006cdf0614b3cee5f65b1296357/bin/create_bag.rb#L37

Currently preservation_robots has the right approach: https://github.com/sul-dlss/preservation_robots/blob/32513e9a0a465006cdf0614b3cee5f65b1296357/lib/robots/sdr_repo/preservation_ingest/base.rb#L55-L62

Perhaps it's possible to add an API endpoint to PreservationCatalog / PreservationClient that can return us the needed data rather than running some of the code locally and some of it remotely.

**Comment by ndushay** [comment]
This is related to multiple-moab;  there is no way to know in moab-versioning which is the primary moab.

**Comment by ndushay** [comment]
closing as we are removing the multiple moab instance code instead.  See issue #198
