### ISSUE TITLE
allow Moab::StorageObjectVersion#ingest_dir and #ingest_file to take a caller supplied value for their use_links parameter

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/moab-versioning#200]
These are called by `Moab::StorageObject#ingest_bag` (which is called by pres robots [`Robots::SdrRepo::PreservationIngest::UpdateMoab#update_moab`](https://github.com/sul-dlss/preservation_robots/blob/da609e494bd91511b65649cc4134f74325ff885e/lib/robots/sdr_repo/preservation_ingest/update_moab.rb#L26)).

Making this parameter accessible will allow pres robots to supply a flag that lets it use the existing copy option when creating a new Moab version, instead of the default hardlinking behavior, which we hope will make our preservation system play better with Ceph backed storage on which our preservation content sits.

connects with (and blocks) https://github.com/sul-dlss/preservation_robots/issues/405

see https://github.com/sul-dlss/moab-versioning/blob/1cfe59cfb4f9fea7a1cc35b936a8f5a7ddd94029/lib/moab/storage_object.rb#L62-L78

and https://github.com/sul-dlss/moab-versioning/blob/85911a0b48aeca63a79ae339a86c88c989161fdd/lib/moab/storage_object_version.rb#L141-L180

**Comment by jmartin-sul** [comment]
i know proliferating params that just get passed through is a bit of a code smell, but adding the param to `ingest_bag` and `ingest_bag_data` and passing it through to `ingest_dir`/`ingest_file` is probably the easiest way to get this done?  but i'd be open to other ideas (e.g. something config based).

**Comment by jmartin-sul** [comment]
if we switched the default behavior of the moab-versioning gem to copy instead of hardlink, we'd want to cut a new major version, as we may have one or two external consumers of the gem (or, we should confirm that we don't have active external consumers -- most of the non-DLSS [github listed dependents](https://github.com/sul-dlss/moab-versioning/network/dependents) look like idle forks of DLSS codebases, but [Digital Repository of Ireland seems like a possible active consumer, currently pinned to `~> 4.4`](https://github.com/Digital-Repository-of-Ireland/dri-app/blob/5e73a5bd58311ff1d061c6398f00a8ef6915603c/Gemfile#L46)).

**Comment by ndushay** [comment]
@jmartin-sul I just read your note;  I released the change as 5.1.0.   If it should be 6.0.0 ... mea culpa.

**Comment by jmartin-sul** [comment]
> @jmartin-sul I just read your note; I released the change as 5.1.0. If it should be 6.0.0 ... mea culpa. Feel free to release 6.0.0 immediately if you have strong feelings. I do not. The external users ... are all forks of our repos anyway, I imagine.

i think that's fine.  afaict the default behavior remains the same, and existing code has to change slightly to take advantage of the new mode of operation.
