### ISSUE TITLE
allow subfolders in the content directory to use any name the filesystem allows

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/moab-versioning#258]
It appears that moab-versioning does not allow these names for the top-level folders of a deposited hierarchy:

- data
- metadata
- content
- manifests

I attempted to accession a hierarchy where the top folder is named data:
```
data/
├── content
│   ├── data
│   │   └── level3.txt
│   └── level2.txt
└── level1.txt
```
This all seemed to work correctly except `moab-versioning` threw this error after the files were copied into preservation:
```
 Error: validate-moab : Problem with Moab validation run on preservation-catalog-qa-02.stanford.edu: [{13=>"Version v0001: content directory has forbidden sub-directory name: vnnnn or [\"data\", \"manifests\", \"content\", \"metadata\"]"}] 
```
The Moab looks like it has the correct structure:
```
yy248yb2831/
└── v0001
    ├── data
    │   ├── content
    │   │   └── data
    │   │       ├── content
    │   │       │   ├── data
    │   │       │   │   └── level3.txt
    │   │       │   └── level2.txt
    │   │       └── level1.txt
    │   └── metadata
    │       ├── cocina.json
    │       ├── contentMetadata.xml
    │       └── versionMetadata.xml
    └── manifests
        ├── fileInventoryDifference.xml
        ├── manifestInventory.xml
        ├── signatureCatalog.xml
        ├── versionAdditions.xml
        └── versionInventory.xml
```
The `data` folder that is part of the content is correctly located as a subfolder of the `content` folder and should not interfere with validation.

Sample druid in QA: https://argo-qa.stanford.edu/view/druid:yy248yb2831

**Expected outcome**

The Moab should be considered valid with any directory name in the content folder. There should be no prohibition on content directory names except for those enforced at the filesystem level.

We especially shouldn't prevent people from naming their folders "data".

**Comment by ndushay** [comment]
There will need to be careful tests to ensure the folders that are part of the structure of the Moab are sacrosanct.

**Comment by mjgiarlo** [comment]
@ndushay @andrewjbtw I have a PR ready: https://github.com/sul-dlss/moab-versioning/pull/261 I'm not sure what else I/we should do to test it, but if you have thoughts, I'm all ears. :)

**Comment by andrewjbtw** [comment]
@mjgiarlo I can test this on stage. I have sample data that has been getting caught in the validation.

**Comment by mjgiarlo** [comment]
@andrewjbtw thx!
