### ISSUE TITLE
SPIKE: Test using Ox instead of nokogiri in content diffing for better performance

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/moab-versioning#266]
Testing on stage has revealed that some objects with many files will time out in the Shelve step (run as a job in DSA). 

See https://app.honeybadger.io/projects/50568/faults/86326783

The timeout occurs when the shelving job in DSA makes a call to a preservation-catalog API endpoint (via the preservation-client) to determine what needs to be shelved.  This call on the preservation-catalog server can take a long time to complete, as it has to parse the contentMetadata XML passed to it by DSA.   It does with nokogiri, which takes a long time for very large blobs of XML.

As a response to this, we are increasing the timeout for preservation-catalog calls: https://github.com/sul-dlss/preservation-client/pull/92

However, even with this increased timeout, some objects on stage continue to timeout.

Some example objects in stage:

druid='druid:pp270vv9568' # 10k files...works
druid='druid:kh844yz4077' # 9k files...doesn't work
druid='druid:gs534db6435' # 25k files... works

Since nokogiri seems to be one of the bottlenecks, this spike would look at the use of nokogiri in the content diffing methods used by the API call that is timing out and see if any performance benefit can be gained by switching to a different XML parsing library (like ox).

Code Archeology:

1. The line in DSA that throws the HB alert is the call to preservation-catalog that times out: https://github.com/sul-dlss/dor-services-app/blob/main/app/services/shelving_service.rb#L48
2. This method in preservation-client calls the preservation-catalog API: https://github.com/sul-dlss/preservation-client/blob/main/lib/preservation/client/objects.rb#L25-L29
3. This method in preservation catalog calls a service wrapper: https://github.com/sul-dlss/preservation_catalog/blob/main/app/controllers/objects_controller.rb#L97-L108
4. The service wrapper then invokes a method in moab-versioning: https://github.com/sul-dlss/preservation_catalog/blob/main/app/services/moab_on_storage/storage_services_wrapper.rb#L15-L20
5. This is the method in moab-versioning invoked:  https://github.com/sul-dlss/moab-versioning/blob/main/lib/stanford/storage_services.rb#L29-L47
6. It then invokes this: https://github.com/sul-dlss/moab-versioning/blob/main/lib/stanford/content_inventory.rb#L20-L30
7. And finally gets here to parse the XML: https://github.com/sul-dlss/moab-versioning/blob/main/lib/stanford/content_inventory.rb#L37-L59

Testing on the rails console on preservation-catalog, starting with this druid on stage: druid:kh844yz4077, and then working your way over to preservation-catalog and running the various steps reveals that the `group_from_cm` method in moab-versioning (step 7 above) is expensive computationally, as it is where the XML parsing occurs.  Previous steps also have a time cost, but I suspect it's the XML parsing that is the most expensive.

**Comment by peetucket** [comment]
Rails console testing on `dor-services-app-stage-a`:

```
druid='druid:kh844yz4077' # 9k files

cocina_object = CocinaObjectStore.find(druid)

# takes 20-30 seconds to run:
content_metadata = Cocina::ToXml::ContentMetadataGenerator.generate(druid: cocina_object.externalIdentifier, structural: cocina_object.structural, type: cocina_object.type)

# this lets you dump the contentMetadata to a ruby object ... you will need this on preservation-catalog to continue the rails console testing:
File.open("tmp/content_metadata_#{druid.delete_prefix('druid:')}.dump", 'wb') { |f| f.write(Marshal.dump(content_metadata)) }

# this is the API call that DSA makes and will timeout 
inventory_diff = Preservation::Client.objects.content_inventory_diff(druid: cocina_object.externalIdentifier, content_metadata:, subset: 'preserve')
inventory_diff.group_difference('content')
```

Rails console testing on `preservation-catalog-web-stage-01.stanford.edu`:

```
druid='druid:kh844yz4077' # 9k files
subset = 'preserve'
obj_version=nil # this is what the DSA call sends

# move that file you generated on DSA to the pres-cat server using SFTP so you can load it up:
content_metadata = Marshal.load(File.read("tmp/content_metadata_#{druid.delete_prefix('druid:')}.dump"))

# this is what the API call is doing, and it takes a long while (longer than 8 mins), hence the timeout:
result = MoabOnStorage::StorageServicesWrapper.content_diff(druid, content_metadata, subset, obj_version)
```

**Comment by mjgiarlo** [comment]
I'm assigning this to myself for spiking during unscheduled week (next week).

**Comment by mjgiarlo** [comment]
I bumped preservation-client to 5.1.1 in DSA to pick up the read_timeout bump, and made some performance tweaks in moab-versioning, and ☝🏻 now completes for me in the DSA console. I benchmarked it and it appears to have taken 217 seconds:

```ruby
Benchmark.measure { inventory_diff = Preservation::Client.objects.content_inventory_diff(druid: cocina_object.externalId
entifier, content_metadata:, subset: 'preserve') }
 => 
#<Benchmark::Tms:0x00007f20b4bdbd80
 @cstime=0.0,                                                       
 @cutime=0.0,                                                       
 @label="",
 @real=217.02734979987144,
 @stime=0.011813999999999991,
 @total=1.6035340000000022,
 @utime=1.5917200000000022>
```

**Comment by mjgiarlo** [comment]
# Profiling 

## Results

Here are screenshots of successive `ruby-prof` runs on the slow operation @peetucket super helpfully documented above.

### Current state

![screenshot_before](https://user-images.githubusercontent.com/131982/215150568-cf3aa100-d085-4170-9253-7df6e2e1af81.png)

### Swapping in Ox for Nokogiri when content diffing

![screenshot_after_ox](https://user-images.githubusercontent.com/131982/215150629-125b8e25-4de2-42e9-9116-8a8177019446.png)

### Making surgical performance-related changes to moab-versonining based on profiling

![screenshot_after_mv_perf_tweaks](https://user-images.githubusercontent.com/131982/215150753-3cd4e6bc-f288-45c5-afb3-7646716492cb.png)

## Methodology

### First, in prescat:

1. Create a new throw-away branch
2. Add `ruby-prof` to `Gemfile`
3. `bundle install`
4. Add `require 'ruby-prof'` to `lib/tasks/prescat.rake`
5. Copy/paste the operation that times out into a new rake task (see `Task Code` below)
6. Commit/push/deploy to stage
7. SSH to a stage box and run the rake task, copying the callstack HTML from your terminal into a local file which you can load in your browser to analyze and compare to subsequent runs

#### Task Code

```ruby
desc 'profile content diffing a large druid'
task profile: :environment do
  # this file was generated on DSA and SFTPed to the stage-01
  content = Marshal.load(File.read('/tmp/content_metadata_kh844yz4077.dump')) # rubocop:disable Security/MarshalLoad
  result = RubyProf.profile do
    # on preservation-catalog-web-stage-01
    MoabOnStorage::StorageServicesWrapper.content_diff(
      'druid:kh844yz4077',
      content,
      'preserve',
      nil
    )
  end
  RubyProf::CallStackPrinter.new(result).print($stdout)
end
```

### Remainder of process

1. Make changes to moab-versioning, commit, push
2. Point prescat at moab-versioning GitHub branch and `bundle`
3. Commit/push/deploy to stage
4. SSH in and run the profiler again as above

**Comment by mjgiarlo** [comment]
# Benchmarking

## Before moab-versioning changes

```ruby
 =>    
#<Benchmark::Tms:0x000055c0d0f4ccc0
 @cstime=0.0,
 @cutime=0.0,
 @label="",
 @real=1876.8203903958201,
 @stime=0.277312,
 @total=1875.9800639999999,
 @utime=1875.702752> 
```

**Comment by mjgiarlo** [comment]
@sul-dlss/infrastructure-team Long story short: some of these take so long (on the other of twenty minutes) that bumping timeouts around our stack is not a viable solution for the problem. We need to discuss architecture changes, ideally in the context of the SDR assessment that @andrewjbtw drafted.

**Comment by mjgiarlo** [comment]
Superseded by https://github.com/sul-dlss/dor-services-app/issues/4359
