### ISSUE TITLE
hold "how to set up, start, post a demo" training

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/moab-versioning#36]
I bought this up at sprint-ops and it was decided that this should just get set up, with a room and a notice sent to dlss-all (?) to invite whomever wants to come.    It *may* be that it's a short meeting;  it *may* be that there won't be a lot of interest.

Note that I mentioned Peter's excellent documentation and said how helpful it was, but we still failed.  Twice.

If we have any suggested updates to Peter's google doc, I'm sure he would give edit permission or at least address comments to the doc.

**Comment by SaravShah** [comment]
https://docs.google.com/document/d/1NqNE9UIU6yAz7S35OmcgLqcJj57BGtkNT_6YHGHfLik/edit
