### ISSUE TITLE
increase read chunk size for checksum computation (see pcc #96)

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/moab-versioning#53]
https://github.com/sul-dlss/moab-versioning/blob/2beb8ed8448c5a3952e75bd80a59ecf897ab154f/lib/moab/file_signature.rb#L144-L163

Julian says "I'd up that buffer to 128 or 256K."

I believe Tommy is performance testing against at 46K file;  perhaps we can get some data on what to choose.

**Comment by ndushay** [comment]
just do it, or wait for data from sul-dlss/preservation_core_catalog#96

**Comment by julianmorley** [comment]
Just do it! Or else get a 1Gb test file and do A/B testing...make sure if you opt for the testing route to clear out the page cache between tests, otherwise you'll be pulling the file from RAM not from disk.

**Comment by tingulfsen** [comment]
See sul-dlss/preservation_core_catalog#116. It looks like checksum calculation is bound by CPU, not by file I/O, so closing this ticket for now.
