### ISSUE TITLE
README shouldn't refer to druids in Moab context

### ISSUE THREAD

**Issue by tallenaz** [sul-dlss/moab-versioning#87]

**Comment by ndushay** [comment]
![druid in README.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5522c457e2d8b81e00d2eea6/125516c66e82c728ace21e0d46ec868f2a86c3a081a98d668579ddb16b0a65633b0ba92e7391a172fd1722585b0b46a4495a0c16aaab8f2ba6b03e74db0e59bfd97f4366846c4ff8e7df46f554f832815d84bfb68b49c1e83d2cef8e884b3916060ac4.png)
