### ISSUE TITLE
(MV) Revision to validity check - data/content is an optional directory

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/moab-versioning#89]
The data/content directory is optional since (a) the object may not have content, and (b) a version may have no new content. MOAB omits the directory rather than creating an empty directory.

**Comment by SaravShah** [comment]
-Update RSpec to use .include instead of .eq

**Comment by LynnMcRae** [comment]
For the record, while the data/metadata directory is technically optional for similar reasons, there is no case where you can version an object without some metadata changes since the version number itself is part of that.  It is effectively required and should be checked.

**Comment by ndushay** [comment]
@SaravShah is this already in progree by you, or is it avail for someone else to work on?

**Comment by SaravShah** [comment]
@ndushay No i'm not working on this currently.

**Comment by ndushay** [comment]
addressed by #92
