### ISSUE TITLE
(MV)  We MAY need a way to run as fail fast OR  fail thoroughly

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/moab-versioning#91]
Currently, the MV code is designed to stop running checks after it encounters an error.  Options:

1. MV stops after it encounters an error
2. MV continues to look for errors after it encounters it's first error (if it can:  e.g. if there are no version directories, it can't find files inside them, but if there is any version directory with a manifestInventory.xml file, then we can do a D2D check.
3. We have a setting or an argument that indicates whether to fail fast or look for all the errors it can find.

---

This ticket started as:  "(D2D) Run D2D whenever object_id is avail, not only when MV checks pass"

``` 
errors.concat super
errors.concat(identify_druid) if errors.empty?
 ```
- So Instead of saying empty, maybe say if errors includes the error codes or excludes the error codes - then i can actually run D2D even if there are errors in MV.

- Run identify_druid whenever we can get the object_id from manifestInventory.xml

**Comment by ndushay** [comment]
I took a stab at a "validation dependency" diagram:  https://docs.google.com/drawings/d/1HOE0Tt-OmF6BYCmhC3vU8dCCJlfi-JLUmAq1w2bhJhs

**Comment by SaravShah** [comment]
it looks awesome!

**Comment by jmartin-sul** [comment]
looks good to me too

**Comment by ndushay** [comment]
For now, we are going to go with "fail fast" for seeding the catalog.  After we have a sense of how many moabs are failing, and why (first failure, anyway), we may decide to have seeding fail thoroughly.

In any case, we know we will want a way to fail thoroughly when humans are trying to fix invalid moabs.   We may want to fail thoroughly in other contexts:

Fail fast?
- seeding the catalog
- M2C existence check
- C2M existence check?
- etc.

Fail thoroughly?
- ingest robot adding version, if we are validating moabs here
- humans wokring on a moab
- etc.

**Comment by atz** [comment]
This is pretty old and predates almost all our implementation.  Specifically, moving most of the checks to asynchronous basis means that there is no "fast" option.  

I think we are satisfied with the system as currently operating.  Please reopen if there is anything remaining to this question.
