### ISSUE TITLE
consider setting tz explicitly to avoid mixing time zones

### ISSUE THREAD

**Issue by tallenaz** [sul-dlss/moab-versioning#93]

**Comment by ndushay** [comment]
can you give more context for this ticket?   where are time zones in a moab object?  why would they become mixed?  Where would we set the timezone explicitly?  

Or is it possible this ticket was meant to be on preservation_catalog  github repo?  If so, I remain confused as to what this ticket is about.

**Comment by tallenaz** [comment]
Closing this, as it got created in the wrong repo. I'll follow up with another more detailed ticket in the right repo.
