### ISSUE TITLE
(MV) Fail fast tweak: StorageObjectValidator.check_correctly_formed_moabs

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/moab-versioning#94]
Line #99 can be refactored to say... if there are EXPECTED_DATA_SUB_DIRS then run `check_required_manifest_files` if there are not the EXPECTED_DATA_SUB_DIRS then don't run `check_required_manifest_files`. RIght now the method will run either way.

**Comment by ndushay** [comment]
See also #91 (do we run as many MV checks as possible, or fail fast?)

**Comment by ndushay** [comment]
I believe #92 addressed this.
